import pandas as pd

df=pd.read_csv("C:\\Users\hp\OneDrive\Desktop\data-1.csv")

mean_value=df['Calories'].mean()
median_value=df['Calories'].median()
mode_value=df['Calories'].mode()
min_value=df['Calories'].min()
max_value=df['Calories'].max()
sum_value = df['Calories'].sum()
count_value=df['Calories'].count()
std_value=df['Calories'].std()
var_value=df['Calories'].var()
quantile_Value=df['Calories'].quantile(.75)


print(df)
print("--------------------------------------------------")
print("Performing on Calories:")
print('Mean Value: ' + str(mean_value))
print('Median Value: '+str(median_value))
print('Mode Value: '+str(mode_value))
print('Minimum Value: '+str(min_value))
print('Maximum Value: '+str(max_value))
print('Sum Value: '+str(sum_value))
print('Count Value: '+str(count_value))
print('Standard Deviation Value: '+str(std_value))
print('Variance Value: '+str(var_value))
print('quantile_Value: '+str(quantile_Value))
print("--------------------------------------------------")

mean_value=df['Pulse'].mean()
median_value=df['Pulse'].median()
mode_value=df['Pulse'].mode()
min_value=df['Pulse'].min()
max_value=df['Pulse'].max()
sum_value = df['Pulse'].sum()
count_value=df['Pulse'].count()
std_value=df['Pulse'].std()
var_value=df['Pulse'].var()
quantile_Value=df['Pulse'].quantile()


print("Performing on Pulse:")
print('Mean Value: ' + str(mean_value))
print('Median Value: '+str(median_value))
print('Mode Value: '+str(mode_value))
print('Minimum Value: '+str(min_value))
print('Maximum Value: '+str(max_value))
print('Sum Value: '+str(sum_value))
print('Count Value: '+str(count_value))
print('Standard Deviation Value: '+str(std_value))
print('Variance Value: '+str(var_value))
print('quantile Value: '+str(quantile_Value))